# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RunFHASTSimulation
                                 A QGIS plugin
 This plugin runs a FHAST simulation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-17
        copyright            : (C) 2024 by Peter Dudley
        email                : pndphd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RunFHASTSimulation class from file RunFHASTSimulation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .run_fhast_simulation import RunFHASTSimulation
    return RunFHASTSimulation(iface)
