# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FHASTFile
                                 A QGIS plugin
 Loades the templet with dummy input files
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-06
        copyright            : (C) 2024 by Peter Dudley
        email                : pndphd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FHASTFile class from file FHASTFile.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fhast_file import FHASTFile
    return FHASTFile(iface)
