del "%OSGEO4W_STARTMENU%\QGIS Desktop 3.16.11 with GRASS 7.8.5.lnk"
del "%OSGEO4W_STARTMENU%\QGIS Browser 3.16.11 with GRASS 7.8.5.lnk"
rmdir "%OSGEO4W_STARTMENU%"
del "%OSGEO4W_DESKTOP%\QGIS Desktop 3.16.11 with GRASS 7.8.5.lnk"
del "%OSGEO4W_DESKTOP%\QGIS Browser 3.16.11 with GRASS 7.8.5.lnk"
rmdir "%OSGEO4W_DESKTOP%"
del "%OSGEO4W_ROOT%\bin\qgis-ltr-grass7.bat"
del "%OSGEO4W_ROOT%\bin\qgis-ltr-bin-g7.exe"
del "%OSGEO4W_ROOT%\bin\qgis-ltr-bin-g7.vars"
del "%OSGEO4W_ROOT%\bin\qgis-ltr-bin-g7.env"
