del "%OSGEO4W_STARTMENU%\QGIS Desktop 3.16.11.lnk"
del "%OSGEO4W_STARTMENU%\QGIS Browser 3.16.11.lnk"
del "%OSGEO4W_STARTMENU%\Qt Designer with QGIS 3.16.11 custom widgets.lnk"
rmdir "%OSGEO4W_STARTMENU%"
del "%OSGEO4W_DESKTOP%\QGIS Desktop 3.16.11.lnk"
del "%OSGEO4W_DESKTOP%\QGIS Browser 3.16.11.lnk"
del "%OSGEO4W_DESKTOP%\Qt Designer with QGIS 3.16.11 custom widgets.lnk"
rmdir "%OSGEO4W_DESKTOP%"
del "%OSGEO4W_ROOT%\bin\qgis-ltr.bat"
del "%OSGEO4W_ROOT%\bin\qgis-ltr-bin.vars"
del "%OSGEO4W_ROOT%\bin\qgis-ltr-bin.env"
del "%OSGEO4W_ROOT%\bin\qgis-ltr-designer.bat"
del "%OSGEO4W_ROOT%\apps\qgis-ltr\python\qgis\qgisconfig.py"
del "%OSGEO4W_ROOT%\apps\qgis-ltr\bin\qgis.reg"
del /s /q "%OSGEO4W_ROOT%\apps\qgis-ltr\python\*.pyc"
