# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CompareRuns
                                 A QGIS plugin
 Compars two simmilar FHAST runs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-12
        copyright            : (C) 2025 by Peter N. Dudley
        email                : pndphd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CompareRuns class from file CompareRuns.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .compare_runs import CompareRuns
    return CompareRuns(iface)
